#pragma once
#include "LocalizationData.h"

namespace Localizations {
    inline LocalizationData GetLocalization_ZH() {
        return {
            .version = LocalizationData::LOCALIZATION_VERSION,
            .translations = {
                {"entity", {
                    {"Unknown", "未知"},

                    {"LocalPlayer", "我自己"}, // Not used
                    {"EnemyPlayer", "猎手"},
                    {"FriendlyPlayer", "队友"},
                    {"DeadPlayer", "死亡"},

                    {"Butcher", "屠夫"},
                    {"Assassin", "刺客"},
                    {"Scrapbeak", "废铁喙"},
                    {"Spider", "蜘蛛"},
                    {"Rotjaw", "腐颚"},
                    {"Hellborn", "地狱生物"},

                    {"CashRegister", "收银机"},
                    {"GoldCashRegister", "黄金收银机"},

                    {"Pouch", "钱袋"},
                    {"Poster", "海报"},
                    {"WorkbenchUpgrade", "蓝图"},
                    {"WorkbenchOil", "枪油"},
                    {"Trait", "特性"},
                    {"Sealed Trait", "封印特性"},

                    {"ResupplyStation", "补给站"},
                    {"ExtractionPoint", "撤离点"},
                    {"Clue", "线索"},

                    {"BearTrap", "捕熊夹"},
                    {"TripMine", "绊雷"},
                    {"DarksightDynamite", "C4"},

                    {"OilBarrel", "油桶"},
                    {"GunpowderBarrel", "火药桶"},
                    {"BioBarrel", "毒气桶"},

                    {"AmmoSwapBox", "弹药替换箱"},
                    {"SpitzerBullets", "尖头弹"},
                    {"PoisonBullets", "毒药弹"},
                    {"HighVelocityBullets", "高速弹"},
                    {"IncendiaryBullets", "燃烧弹"},
                    {"DumDumBullets", "达姆弹"},
                    {"ExplosiveBullets", "爆炸弹"},
                    {"FMJBullets", "全金属弹"},
                    {"PoisonBolts", "毒药弩箭"},
                    {"ExplosiveBolts", "爆炸弩箭"},
                    {"IncendiaryShells", "燃烧霰弹"},
                    {"PennyShotShells", "便士霰弹"},
                    {"FlechetteShells", "箭形霰弹"},
                    {"SlugShells", "独头弹"},

                    {"SupplyBox", "补给箱"},
                    {"AmmoCrate", "弹药箱"},
                    {"SpecialAmmoCrate", "特殊弹药箱"},
                    {"CompactAmmoPackage", "小口径弹药包"},
                    {"MediumAmmoPackage", "中口径弹药包"},
                    {"LongAmmoPackage", "大口径弹药包"},
                    {"ShotgunAmmoPackage", "霰弹弹药包"},
                    {"Medkit", "医疗包"},

                    {"Event", "活动物品"},
                }},
                {"menu", {
                    {"window.name", "Hunt DMA"},
                    {"tabs.PlayerESP", "玩家透视"},
                    {"tabs.BossesESP", "Boss透视"},
                    {"tabs.SupplyESP", "补给透视"},
                    {"tabs.BBESP", "血债透视"},
                    {"tabs.TrapESP", "陷阱透视"},
                    {"tabs.POIESP", "POI透视"},
                    {"tabs.TraitESP", "特性透视"},
                    {"tabs.Overlay", "叠加层"},
                    {"tabs.Aimbot", "自瞄"},
                    {"tabs.Settings", "设置"},
                    {"tabs.Hotkeys", "快捷键"},
                    {"hotkey.SelectKey", "选择按键"},
                    {"hotkey.Instructions", "按任意键或点击取消"},
                    {"esp.Meters", " [{}m]"},
                    {"general.Enable", "启用"},
                    {"general.TextColor", "文字颜色"},
                    {"general.Name", "名称"},
                    {"general.Distance", "距离"},
                    {"general.MaxDistance", "最大距离"},
                    {"general.TextSize", "文字大小"},
                    {"general.Meters", "%d 米"},
                    {"general.Pixels", "%d 像素"},
                    {"general.?", "(?)"},
                    {"players.HP", "血量"},
                    {"players.ShowDead", "显示死亡玩家"},
                    {"players.DeadMaxDistance", "死亡玩家最大距离"},
                    {"players.DrawFriendlyHP", "显示队友血量"},
                    {"players.FriendColor", "队友颜色"},
                    {"players.ChamMode", "染色模式"},
                    {"players.WriteChams", "写入染色（启用/更新）"},
                    {"players.DrawFrames", "绘制边框"},
                    {"players.FramesColor", "边框颜色"},
                    {"players.DrawHead", "在边框中绘制头部"},
                    {"players.HeadCircleSize", "头部圆圈大小"},
                    {"players.HeadCircleOffsetX", "头部圆圈X偏移"},
                    {"players.HeadCircleOffsetY", "头部圆圈Y偏移"},
                    {"players.DrawHealth", "绘制血条"},
                    {"players.Snaplines", "连线"},
                    {"chams.OutlineRed", "描边红色"},
                    {"chams.OutlineBlue", "描边蓝色"},
                    {"chams.OutlineYellow", "描边黄色"},
                    {"chams.OutlineOrange", "描边橙色"},
                    {"chams.OutlineCyan", "描边青色"},
                    {"chams.OutlineMagenta", "描边品红"},
                    {"chams.OutlineWhite", "描边白色"},
                    {"chams.FilledRed", "填充红色"},
                    {"chams.FilledBlue", "填充蓝色"},
                    {"chams.FilledYellow", "填充黄色"},
                    {"chams.FilledOrange", "填充橙色"},
                    {"chams.FilledCyan", "填充青色"},
                    {"chams.FilledMagenta", "填充品红"},
                    {"chams.FilledWhite", "填充白色"},
                    {"supply.AmmoTypes", "弹药类型："},
                    {"supply.ShowSpecialAmmo", "显示特殊弹药"},
                    {"supply.ShowCompactAmmo", "显示小口径弹药"},
                    {"supply.ShowMediumAmmo", "显示中口径弹药"},
                    {"supply.ShowLongAmmo", "显示大口径弹药"},
                    {"supply.ShowShotgunAmmo", "显示霰弹弹药"},
                    {"supply.OtherTypes", "其他类型："},
                    {"supply.ShowAmmoSwapBox", "显示弹药替换箱"},
                    {"supply.ShowMedkit", "显示医疗包"},
                    {"supply.ShowYellowSupplyBox", "显示黄色补给箱"},
                    {"bb.HelpMarker", "黄金收银机透视"},
                    {"traps.TrapColor", "陷阱颜色"},
                    {"traps.BarrelColor", "桶颜色"},
                    {"traps.Traps", "陷阱："},
                    {"traps.ShowBeartraps", "显示捕熊夹"},
                    {"traps.ShowTripmines", "显示绊雷"},
                    {"traps.ShowDarksightDynamite", "显示暗视炸药"},
                    {"traps.Barrels", "桶："},
                    {"traps.ShowGunpowderBarrels", "显示火药桶"},
                    {"traps.ShowOilBarrels", "显示油桶"},
                    {"traps.ShowBioBarrels", "显示毒气桶"},
                    {"poi.MainPOIs", "主要POI："},
                    {"poi.ShowResupplyPoints", "显示补给站"},
                    {"poi.ShowExtractionPoints", "显示撤离点"},
                    {"poi.ShowCashRegisters", "显示收银机"},
                    {"poi.ShowPouches", "显示钱袋"},
                    {"poi.ShowClues", "显示线索"},
                    {"poi.AdditionalPOIs", "附加POI："},
                    {"poi.ShowPosters", "显示海报"},
                    {"poi.ShowBlueprints", "显示蓝图"},
                    {"poi.ShowGunOil", "显示枪油"},
                    {"poi.ShowSeasonalDestructibles", "显示季节性可破坏物"},
                    {"poi.ShowSeasonalDestructiblesInfo", "南瓜、气球等"},
                    {"traits.Other", "不在普通游戏中出现的其他特性"},
                    {"overlay.ResolutionSettings", "分辨率设置："},
                    {"overlay.OverrideResolution", "覆盖分辨率"},
                    {"overlay.ScreenWidth", "屏幕宽度"},
                    {"overlay.ScreenHeight", "屏幕高度"},
                    {"overlay.Radar", "雷达："},
                    {"overlay.DrawMapRadar", "绘制地图雷达"},
                    {"overlay.DrawSelf", "绘制自身"},
                    {"overlay.PlayerColor", "玩家颜色"},
                    {"overlay.EnemyColor", "敌人颜色"},
                    {"overlay.RadarScale", "地图缩放"},
                    {"overlay.RadarX", "地图位置X"},
                    {"overlay.RadarY", "地图位置Y"},
                    {"overlay.PlayerList", "玩家列表："},
                    {"overlay.ShowPlayerList", "显示玩家列表"},
                    {"overlay.PlayerListColor", "玩家列表颜色"},
                    {"overlay.PlayerListSize", "玩家列表文字大小"},
                    {"overlay.FPSCounter", "帧率计数器："},
                    {"overlay.ShowFPS", "显示帧率"},
                    {"overlay.FPSColor", "帧率颜色"},
                    {"overlay.FPSFontSize", "帧率字体大小"},
                    {"overlay.ObjectCounter", "对象计数器："},
                    {"overlay.ShowObjectCount", "显示对象数量"},
                    {"overlay.CountColor", "计数颜色"},
                    {"overlay.CountFontSize", "计数字体大小"},
                    {"overlay.CrosshairSettings", "准星设置："},
                    {"overlay.CrosshairType", "准星类型"},
                    {"overlay.CrosshairSize", "准星大小"},
                    {"overlay.CrosshairColor", "准星颜色"},
                    {"crosshair.None", "无"},
                    {"crosshair.FilledCircle", "实心圆"},
                    {"crosshair.OutlineCircle", "空心圆"},
                    {"crosshair.FilledRect", "实心方块"},
                    {"crosshair.OutlineRect", "空心方块"},
                    {"settings.SaveConfig", "保存配置"},
                    {"settings.SaveConfigPopup", "配置保存成功！"},
                    {"settings.LoadConfig", "加载配置"},
                    {"settings.LoadConfigPopup", "配置加载成功！"},
                    {"settings.Language", "语言"},
                    {"settings.LanguageInfo", "选择界面语言"},
                    {"settings.OverlayMode", "叠加层模式"},
                    {"settings.OverlayModeInfo", "需要重启应用！\n更改后将保存配置并关闭应用。\n\n适用于单机设置。\n将应用绘制在所有窗口之上。\n透明度仅在叠加层模式下可用。\n在Hunt全屏模式下也能正常工作。"},
                    {"settings.PreventRecording", "防止录制"},
                    {"settings.PreventRecordingInfo", "隐藏应用不被录制。\nNvidia ShadowPlay的限制：\n检测到防录制标志的窗口时会停止录制（无法录制击杀）。"},
                    {"settings.UIScale", "界面缩放"},
                    {"settings.UIScaleInfo", "默认值为您的DPI缩放比例。\n需要重启才能生效。"},
                    {"settings.CrosshairLowerPosition", "准星下移位置"},
                    {"settings.CrosshairLowerPositionInfo", "如果您使用准星备用位置，请勾选此项，以便叠加层在正确位置渲染准星。自瞄也会使用此设置。"},
                    {"settings.ShowDevSettings", "显示开发者设置"},
                    {"settings.WriteEntitiesDump", "写入实体转储"},
                    {"settings.WriteEntitiesDumpInfo", "将所有实体类名转储到classes-dump.txt\n重启应用后复选框重置。"},
                    {"settings.OpenCloseMenuKey", "更改菜单开关键"},
                    {"settings.CloseMenuOnEsc", "按Esc关闭菜单"},
                    {"settings.ExitApp", "退出应用"},
                    {"settings.ExitAppInfo", "立即关闭应用"},
                }},
                {"trait", {
                    {"adrenaline", "肾上腺素 (1)"},
                    {"ambidextrous", "双手灵巧 (3)"},
                    {"assailant", "袭击者 (1)"},
                    {"beastface", "兽面 (4)"},
                    {"bladeseer", "刀锋感知 (1)"},
                    {"bloodless", "无血 (3)"},
                    {"boltthrower", "弩手 (3)"},
                    {"bulletgrubber", "捡弹 (4)"},
                    {"bulwark", "壁垒 (2)"},
                    {"conduit", "导体 (5)"},
                    {"dauntless", "无畏 (1)"},
                    {"decoysupply", "诱饵补给 (1)"},
                    {"determination", "决心 (4)"},
                    {"doctor", "医生 (9)"},
                    {"fanning", "扇锤 (8)"},
                    {"fastfingers", "快手 (6)"},
                    {"frontiersman", "边疆人 (5)"},
                    {"gatorlegs", "鳄鱼腿 (3)"},
                    {"ghoul", "食尸鬼 (3)"},
                    {"greyhound", "灵缇 (5)"},
                    {"hornskin", "角皮 (3)"},
                    {"hundredhands", "百手 (2)"},
                    {"ironeye", "铁眼 (3)"},
                    {"kiteskin", "风筝皮 (1)"},
                    {"levering", "杠杆 (7)"},
                    {"lightfoot", "轻足 (5)"},
                    {"magpie", "喜鹊 (1)"},
                    {"martialist", "武术家 (2)"},
                    {"mithridatist", "抗毒者 (3)"},
                    {"packmule", "驮骡 (4)"},
                    {"physician", "内科医生 (5)"},
                    {"pitcher", "投手 (4)"},
                    {"poacher", "偷猎者 (1)"},
                    {"poisonsense", "毒感 (3)"},
                    {"quartermaster", "军需官 (6)"},
                    {"resilience", "韧性 (3)"},
                    {"salveskin", "药膏皮 (3)"},
                    {"scopesmith", "瞄准镜匠 (2)"},
                    {"serpent", "毒蛇 (4)"},
                    {"silentkiller", "无声杀手 (3)"},
                    {"steadyaim", "稳定瞄准 (2)"},
                    {"surefoot", "稳足 (4)"},
                    {"vigilant", "警觉 (1)"},
                    {"vigor", "活力 (3)"},
                    {"vulture", "秃鹫 (2)"},
                    {"whispersmith", "低语匠 (1)"},
                    {"witness", "目击者 (5)"},

                    {"berserker", "狂战士 (!)"},
                    {"deathcheat", "欺死 (!)"},
                    {"necromancer", "死灵法师 (4)"},
                    {"rampage", "狂暴 (!)"},
                    {"relentless", "无情 (!)"},
                    {"remedy", "补救 (!)"},
                    {"shadow", "暗影 (!)"},
                    {"shadowleap", "暗影跃 (!)"},

                    {"blademancer", "刀术师"},
                    {"corpseseer", "尸体预言者"},
                    {"gunrunner", "枪械走私者"}
                }}
            }
        };
    }
}
